### Write a function to calculate the convolution of a kernel with an image. Ignore stride.

In [1]:
import numpy as np

In [32]:
img = np.random.randn(100,100)
kernel = np.random.randn(5,5)
padding = 1

In [33]:
def conv2d (img, kernel, padding):
    new_img_dim = img.shape[0]-kernel.shape[0]+1+padding*2
    new_img = np.zeros((new_img_dim,new_img_dim))
    pad_img = np.zeros((img.shape[0]+padding*2,img.shape[1]+padding*2))
    pad_img[1:pad_img.shape[0]-1,1:pad_img.shape[1]-1]=img
    for y in range (pad_img.shape[0]-5):
        for x in range (pad_img.shape[1]-5):
            block=pad_img[y:y+5,x:x+5]
            new_img[y,x]=np.sum(kernel*block)
    return new_img

In [34]:
conv2d(img,kernel,padding)

array([[  7.39940271,  -2.02262755,  -3.86006114, ...,   4.12656866,
         -2.94297593,   0.        ],
       [  1.98699758, -10.33515793,  -3.11218174, ...,  -5.75485525,
          6.38059287,   0.        ],
       [ -2.57873843,  -3.04804505,   4.28739325, ...,   6.27079227,
         -4.36580864,   0.        ],
       ...,
       [ -2.49362482,  11.37642304,  -0.34325633, ...,   1.74625509,
         10.25680293,   0.        ],
       [ -1.26190757,   8.27647161,  -6.19142515, ...,   1.08036687,
         -7.41882161,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [36]:
# Calculate new image dimensions
new_img_dim = img.shape[0] - kernel.shape[0] + 2 * padding + 1

# Initialize new_img with zeros
new_img = np.zeros((new_img_dim, new_img_dim))

# Create a padded version of the input image
pad_img = np.pad(img, ((padding, padding), (padding, padding)), mode='constant')

# Iterate over the padded image to apply the convolution
for y in range(new_img_dim):
    for x in range(new_img_dim):
        block = pad_img[y:y + kernel.shape[0], x:x + kernel.shape[1]]
        new_img[y, x] = np.sum(kernel * block)

# Print the result
print(new_img)

[[  7.39940271  -2.02262755  -3.86006114 ...   4.12656866  -2.94297593
   -1.80883055]
 [  1.98699758 -10.33515793  -3.11218174 ...  -5.75485525   6.38059287
   -3.81120507]
 [ -2.57873843  -3.04804505   4.28739325 ...   6.27079227  -4.36580864
   -0.02445161]
 ...
 [ -2.49362482  11.37642304  -0.34325633 ...   1.74625509  10.25680293
  -15.33210998]
 [ -1.26190757   8.27647161  -6.19142515 ...   1.08036687  -7.41882161
    1.35490611]
 [  4.12727086  -4.9606421   -0.64870437 ...  -2.3064823    2.91650789
   -0.69997407]]


In [40]:
img1 = np.ones((2,2))
pad_img1 = np.pad(img1, ((padding, padding),(padding, padding)), mode='constant')
img1,pad_img1

(array([[1., 1.],
        [1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]]))

### Write a function to perform max pooling of an image

In [48]:
def max_pool(img,kernel_size):
    new_img = np.zeros((round(img.shape[0]/2), round(img.shape[1]/2)))
    for y in range(0,img.shape[0],2):
        for x in range(0,img.shape[1],2):
            new_img[round(y/2),round(x/2)]=np.max(img[y:y+kernel_size,x:x+kernel_size])
    return new_img

In [49]:
img,max_pool(img,2)

(array([[ 0.63838637,  2.18212498, -0.7087016 , ..., -0.82567285,
          1.02723707,  0.53271852],
        [-1.16028225, -0.22341921, -0.44867893, ...,  0.46276818,
         -1.16422706,  0.13475847],
        [-0.81819584, -0.59360704,  2.45130047, ..., -1.00940513,
          1.26700357, -1.29503141],
        ...,
        [-0.97949594, -1.22539982, -0.02291549, ...,  0.81643358,
          0.96601733,  0.29734102],
        [ 1.91551259, -0.89754706,  0.6968829 , ...,  2.00697945,
         -0.7838804 ,  0.11340846],
        [-1.04409271, -0.38637896,  0.01478406, ..., -0.25546803,
          2.07174596, -0.12288174]]),
 array([[ 2.18212498,  0.83845348,  1.19075268, ...,  1.85350152,
          0.46276818,  1.02723707],
        [-0.59360704,  2.45130047,  0.23560356, ...,  1.16993476,
          1.63039395,  1.26700357],
        [ 1.53681493,  0.1310596 ,  1.5581286 , ...,  1.06049415,
          1.12232556,  0.75698651],
        ...,
        [ 1.62033185,  0.52928548,  1.06856665, ...,  

### Write a class to perform linear regression

In [51]:
class LinearRegression:
    def __init__(self):
        self.slope = None
        self.intercept = None

    def fit(self, X, y):
        n = len(X)
        x_mean = np.mean(X)
        y_mean = np.mean(y)
        numerator = 0
        denominator = 0
        for i in range(n):
            numerator += (X[i] - x_mean) * (y[i] - y_mean)
            denominator += (X[i] - x_mean) ** 2
        self.slope = numerator / denominator
        self.intercept = y_mean - self.slope * x_mean

    def predict(self, X):
        y_pred = []
        for x in X:
            y_pred.append(self.slope * x + self.intercept)
        return y_pred

In [53]:
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
lr = LinearRegression()
lr.fit(X, y)
print(lr.slope)  # Output: 0.6
print(lr.intercept)  # Output: 2.2
y_preds = lr.predict(X)
print(y_pred)

0.6
2.2
[2.8000000000000003, 3.4000000000000004, 4.0, 4.6, 5.2]


#### Calcualte the mean square error of the prediction

In [55]:
sum_sq_err=0
for y_true, y_pred in zip(y,y_preds):
    sum_sq_err += (y_true-y_pred)**2
mse=sum_sq_err/len(y)
print(mse)

0.47999999999999987


### Calculate the logistic regression with numpy

In [57]:
def sigmoid_fn(x):
    return 1/(1+np.exp(x))

In [58]:
sigmoid_fn(5)

0.0066928509242848554