Problem: Fit the data below with a linear regression model

In [5]:
X = [(1,2),(2,5),(3,3),(7,8),(21,25)]
y = [20,25,28,30,50]

### sklearn model

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [76]:
model1 = LinearRegression()
model1.fit(X, y)

LinearRegression()

In [78]:
y_preds = model1.predict(X)
print(y_preds)

[22.659298 23.773872 25.57186  30.986935 50.008038]


In [79]:
mse = mean_squared_error(y, y_preds)
print(mse)

3.089045


### PyTorch model

In [103]:
import torch
import torch.nn as nn

In [127]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)

    def forward(self, x):
        # Forward pass
        out = self.linear(x)
        return out

model2 = LinearModel()

In [128]:
X = torch.tensor(X).type(torch.float)
y=torch.tensor(y).type(torch.float)
print(X,"\n", y)

tensor([[ 1.,  2.],
        [ 2.,  5.],
        [ 3.,  3.],
        [ 7.,  8.],
        [21., 25.]]) 
 tensor([20., 25., 28., 30., 50.])


C:\Users\Peng\AppData\Local\Temp/ipykernel_9536/3093484265.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X).type(torch.float)
C:\Users\Peng\AppData\Local\Temp/ipykernel_9536/3093484265.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y=torch.tensor(y).type(torch.float)


In [129]:
loss_fn = nn.MSELoss() 
optimizer = torch.optim.Adam(params=model2.parameters(),lr=0.05)

In [130]:
torch.manual_seed(42)
epochs = 2000
for epoch in range(epochs):    
    model2.train()
    y_pred = model2(X)
    loss = loss_fn(y_pred, y.reshape(-1, 1))
    if epoch%50==0:
        print(f'{loss.detach().numpy()}')
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

491.0019
186.2034
146.0051
112.335915
85.022865
63.594757
47.238007
35.052387
26.16895
19.810808
15.322426
12.177272
9.971304
8.407397
7.275837
6.434041
5.7882786
5.2785254
4.8669496
4.529629
4.251052
4.020589
3.8304353
3.6743927
3.5472767
3.4445996
3.3624184
3.297274
3.2461464
3.2064197
3.1758676
3.1526198
3.1351159
3.1220791
3.1124794
3.105484
3.1004486
3.096865
3.0943437
3.0925944


In [131]:
y_preds = model2(X)
print(y_preds)

tensor([[22.6460],
        [23.8431],
        [25.5043],
        [30.9423],
        [50.0219]], grad_fn=<AddmmBackward0>)
