Task: fit the data below with a linear regression model

In [5]:
X = [(1,2),(2,5),(3,3),(7,8),(21,25)]
y = [20,25,28,30,50]

### sklearn model

In [105]:
from sklearn.linear_model import LinearRegression

In [106]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [107]:
model.predict(X)

array([22.659298, 23.773872, 25.57186 , 30.986935, 50.008038],
      dtype=float32)

### PyTorch model

In [108]:
import torch
import torch.nn as nn

In [109]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)

    def forward(self, x):
        # Forward pass
        out = self.linear(x)
        return out

In [118]:
model = LinearModel()

In [119]:
X = torch.tensor(X).type(torch.float)
y=torch.tensor(y).type(torch.float)
X,y

C:\Users\Peng\AppData\Local\Temp/ipykernel_1336/1257109701.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X).type(torch.float)
C:\Users\Peng\AppData\Local\Temp/ipykernel_1336/1257109701.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y=torch.tensor(y).type(torch.float)


(tensor([[ 1.,  2.],
         [ 2.,  5.],
         [ 3.,  3.],
         [ 7.,  8.],
         [21., 25.]]),
 tensor([20., 25., 28., 30., 50.]))

In [120]:
# Create the loss function
loss_fn = nn.MSELoss() # MAE loss is same as L1Loss

# Create the optimizer
optimizer = torch.optim.SGD(params=model.parameters(), # parameters of target model to optimize
                            lr=0.001) # learning rate (how much the optimizer should change parameters at each step, higher=more (less stable), lower=less (might take a long time))

In [121]:
torch.manual_seed(42)
epochs = 100
for epoch in range(epochs):
    # Put model in training mode (this is the default state of a model)
    model.train()

    # 1. Forward pass on train data using the forward() method inside 
    y_pred = model(X)

    # 2. Calculate the loss (how different are our models predictions to the ground truth)
    loss = loss_fn(y_pred, y)
    print(loss.detach().numpy())

    # 3. Zero grad of the optimizer
    optimizer.zero_grad()

    # 4. Loss backwards
    loss.backward()

    # 5. Progress the optimizer
    optimizer.step()

671.14185
608.75745
591.7281
586.4026
584.0993
582.5786
581.2627
580.0024
578.7592
577.5234
576.29205
575.0649
573.8415
572.6218
571.40594
570.19366
568.98517
567.78033
566.5792
565.3817
564.18787
562.99774
561.81116
560.62823
559.4489
558.2732
557.1011
555.93243
554.7674
553.60596
552.44806
551.2937
550.14276
548.9954
547.8515
546.71106
545.5741
544.44055
543.31055
542.1839
541.0607
539.9409
538.82446
537.71155
536.6019
535.49567
534.39276
533.29315
532.19696
531.104
530.0144
528.92816
527.8451
526.76544
525.68896
524.6157
523.5458
522.4791
521.41565
520.35535
519.2982
518.2443
517.19366
516.1461
515.10175
514.0605
513.0225
511.98755
510.95575
509.92703
508.90137
507.8788
506.8594
505.84308
504.82977
503.8195
502.81232
501.80807
500.807
499.80878
498.81366
497.82156
496.8323
495.84607
494.86288
493.88257
492.90524
491.93082
490.95935
489.9907
489.02502
488.06226
487.10236
486.14532
485.19125
484.23984
483.29147
482.34583
481.40305
480.46307
